# Generated by Django 3.2.7 on 2021-11-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_customer_transactions', '0003_bms_cu_booking_history_no_of_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='bms_cu_booking_history',
            name='booked_date',
            field=models.DateField(default='2021-11-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bms_cu_booking_history',
            name='booked_time',
            field=models.TimeField(default='12:59:00'),
            preserve_default=False,
        ),
    ]
