# Generated by Django 3.2.7 on 2021-11-14 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lots', '0008_bms_pl_data_pl_description'),
        ('bms_users', '0005_alter_bms_signup_password'),
        ('bms_customer_transactions', '0004_auto_20211108_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='bms_cu_faviorate',
            fields=[
                ('fav_id', models.AutoField(primary_key=True, serialize=False)),
                ('pl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_lots.bms_pl_data')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms_users.bms_signup')),
            ],
        ),
    ]
