# Generated by Django 3.2.7 on 2021-10-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bms_signup',
            name='user_type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
