# Generated by Django 3.2.7 on 2021-10-14 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bms_users', '0002_bms_signup_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bms_signup',
            name='confirm_password',
        ),
    ]
