# Generated by Django 3.2.7 on 2021-10-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_users', '0003_remove_bms_signup_confirm_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bms_signup',
            name='id',
        ),
        migrations.AddField(
            model_name='bms_signup',
            name='user_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
