# Generated by Django 3.2.7 on 2021-10-14 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_users_signup_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_signup',
            name='user_type',
        ),
    ]
