# Generated by Django 3.2.7 on 2021-10-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bms_pl_data',
            fields=[
                ('pl_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('manager_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=100)),
                ('booking_price', models.PositiveIntegerField()),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('email', models.EmailField(max_length=254)),
                ('total_slot_count', models.PositiveIntegerField()),
                ('booked_slot_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='parking_lot',
        ),
    ]
