# Generated by Django 3.2.7 on 2021-10-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lots', '0003_bms_pl_booking_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bms_pl_booking_history',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
