# Generated by Django 3.2.7 on 2021-11-01 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bms_customer_transactions', '0002_auto_20211101_1323'),
        ('bms_users', '0004_auto_20211015_2103'),
        ('parking_lots', '0004_alter_bms_pl_booking_history_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bms_pl_booking_history',
            name='booking_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms_customer_transactions.bms_cu_booking_history'),
        ),
        migrations.AlterField(
            model_name='bms_pl_booking_history',
            name='pl_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_lots.bms_pl_data'),
        ),
        migrations.AlterField(
            model_name='bms_pl_data',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms_users.bms_signup'),
        ),
    ]
