# Generated by Django 3.2.7 on 2021-11-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lots', '0005_auto_20211101_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='bms_pl_data',
            name='pl_image',
            field=models.ImageField(null=True, upload_to='pl-images/'),
        ),
    ]
