# Generated by Django 3.2.7 on 2021-11-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lots', '0006_bms_pl_data_pl_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bms_pl_data',
            name='pl_image',
            field=models.ImageField(default='pl-images/logo.jpg', null=True, upload_to='pl-images/'),
        ),
    ]
